insert into user(phone,reg_time) values("13019515471","2023-03-21");
insert into user(phone,reg_time) values("13019515472","2023-03-21");
insert into user(phone,reg_time) values("13019515473","2023-03-18");
insert into user(phone,reg_time) values("13019515474","2023-03-18");
insert into user(phone,reg_time) values("13019515475","2023-03-18");
insert into user(phone,reg_time) values("13019515477","2023-03-22");
insert into user(phone,reg_time) values("13019515478","2023-03-22");

insert into question(picture,answer,explains) values("pic_test1", 0, "just a test");
insert into question(picture,answer,explains) values("pic_test2", 0, "just a test");
insert into question(picture,answer,explains) values("pic_test3", 0, "just a test");
insert into question(picture,answer,explains) values("pic_test4", 1, "just a test");
insert into question(picture,answer,explains) values("pic_test5", 1, "just a test");
insert into question(picture,answer,explains) values("pic_test6", 1, "just a test");
insert into question(picture,answer,explains) values("pic_test7", 1, "just a test");
insert into question(picture,answer,explains) values("pic_test8", 2, "just a test");
insert into question(picture,answer,explains) values("pic_test9", 2, "just a test");
insert into question(picture,answer,explains) values("pic_test10", 2, "just a test");
insert into question(picture,answer,explains) values("pic_test11", 2, "just a test");
insert into question(picture,answer,explains) values("pic_test12", 2, "just a test");
insert into question(picture,answer,explains) values("pic_test13", 3, "just a test");
insert into question(picture,answer,explains) values("pic_test14", 3, "just a test");
insert into question(picture,answer,explains) values("pic_test15", 3, "just a test");
insert into question(picture,answer,explains) values("pic_test16", 3, "just a test");
insert into question(picture,answer,explains) values("pic_test17", 3, "just a test");
insert into question(picture,answer,explains) values("pic_test18", 3, "just a test");
insert into question(picture,answer,explains) values("pic_test19", 3, "just a test");
insert into question(picture,answer,explains) values("pic_test20", 3, "just a test");
insert into question(picture,answer,explains) values("pic_test21", 0, "just a test");
insert into question(picture,answer,explains) values("pic_test22", 0, "just a test");
insert into question(picture,answer,explains) values("pic_test23", 0, "just a test");
insert into question(picture,answer,explains) values("pic_test24", 1, "just a test");
insert into question(picture,answer,explains) values("pic_test25", 1, "just a test");
insert into question(picture,answer,explains) values("pic_test26", 1, "just a test");
insert into question(picture,answer,explains) values("pic_test27", 1, "just a test");
insert into question(picture,answer,explains) values("pic_test28", 2, "just a test");
insert into question(picture,answer,explains) values("pic_test29", 2, "just a test");
insert into question(picture,answer,explains) values("pic_test30", 2, "just a test");
